# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nL7VbzRvp9E55F7TqPcBLe_ymkonYO_M
"""

# 03 of75 days challenge

import  pandas as pd

df = pd.read_csv("/train.csv")

df

df.head(19)

df.tail(5)

df.describe

del df["Survived"]

df

df.drop(3)

df.drop(4,inplace = True )

df

df.set_index("Name")

df.reset_index()

d = {
    "key1":[1,2,43,45,5,],
    "key2":[6,7,8,8,6]
}
pd.DataFrame(d)

df1 = pd.read_csv("/Youtuber.csv")

df1.isnull().sum()

df.mean()

df.notnull().mean()

